name: Login to AWS using OIDC
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Login to AWS using OIDC
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE: "github-actions-pipeline-role"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Test AWS CLI
      run: |
         aws ec2 describe-instances