name: Login to AWS using OIDC
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Login to AWS using OIDC
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE: "github-actions-pipeline-role"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Confirm logged in user
      run: |
         aws sts get-caller-identity
    - name: Create S£ Bucket as demo
      run: |
         BUCKETNAME=${{ env.AWS_ACCOUNT_ID }}-$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 40 | head -n 1)
         aws s3api create-bucket --bucket $BUCKETNAME